use_frameworks!

platform :ios, '8.0'

target 'jefferyFlutterPod_Example' do
  pod 'jefferyFlutterPod', :path => '../'

  target 'jefferyFlutterPod_Tests' do
    inherit! :search_paths

    
  end
end

flutter_application_path = '../jeffery_flutter_module'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
